threshold: 0.1
threshold_angle: 0.4
# Coordinates are in the North east down frame x -> y and y -> x
wp:
    /px4_1:
          - { x: 0, y: 0, z: -5, yaw: 0 }
          - { x: 4, y: 0, z: -1, yaw: 0 }
          - { x: 5, y: 0, z: -4, yaw: 0 }
